# Utiliser une image de base Node.js
FROM node:18

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY frontend-admin/package*.json ./

# Installer les dépendances
RUN npm install

# Installer Vite
RUN npm install vite

# Installer TailwindCSS CLI
RUN npm install -D tailwindcss@latest postcss autoprefixer

# Initialiser TailwindCSS
RUN npx tailwindcss-cli@latest init

# Copier le reste de l'application
COPY frontend-admin/ .

# Construire l'application pour la production avec Vite
RUN npm run build

# Utiliser une image de base Nginx pour servir l'application
FROM nginx:alpine
COPY --from=0 /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
# Exposer le port 80
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]