FROM node:18

# Créer un répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY backend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY backend/ .

# Exposer le port de l'application
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "start"]